services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
  postgres_db:
    image: postgres
    restart: always
    ports:
    - '5433:5432'
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=brawl_tournaments
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
    - '6379:6379'
    environment:
      - REDIS_PORT=6379

volumes:
  postgres_data: