FROM node:20-alpine

WORKDIR /usr/src/app

COPY . .

RUN yarn install --frozen-lockfile

RUN yarn run build

RUN yarn global add pm2

RUN rm -rf ./src

EXPOSE 3001

CMD ["pm2-runtime", "dist/main.js"]
