name: Build and Deploy Backend Docker Image

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Log in to Docker registry
    - name: Log in to Docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t bs-tournaments-backend:${{ github.sha }} -f Dockerfile.prod .

    # Push the Docker image to the registry
    - name: Push Docker image
      run: |
        docker tag bs-tournaments-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/bs-tournaments-backend:${{ github.sha }}
        docker tag bs-tournaments-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/bs-tournaments-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/bs-tournaments-backend:${{ github.sha }}
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.7.0
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to server
      env:
        DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/bs-tournaments-backend:${{ github.sha }}
        # SERVER_WORK_DIR in format "/path-to-dir", e.g. "/usr/src/app"
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
        docker pull $DOCKER_IMAGE
        docker stop bs-tournaments-backend || true
        docker rm bs-tournaments-backend || true
        # Create the directory on the server if it doesn't exist
        mkdir -p ${{ secrets.SERVER_WORK_DIR }}/uploaded/images
        # Run the container with a bind mount for the images directory
        docker run -d --name bs-tournaments-backend \
          --env-file ${{ secrets.SERVER_WORK_DIR }}/.env \
          -p 3001:3001 \
          -v ${{ secrets.SERVER_WORK_DIR }}/uploaded/images:/usr/src/app/uploaded/images \
          $DOCKER_IMAGE
        EOF
