name: Build and Deploy Backend Docker Image

on:
  push:
    branches:
      - prod

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker registry
      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bs-tournaments-backend:${{ github.sha }} -f Dockerfile.prod .

      # Push the Docker image to the registry
      - name: Push Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/bs-tournaments-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/bs-tournaments-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bs-tournaments-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bs-tournaments-backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      # Install SSH Key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.7.0
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      # Add Known Hosts
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Deploy to the Server
      - name: Deploy to server
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/bs-tournaments-backend:${{ github.sha }}
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
          cd ${{ secrets.SERVER_WORK_DIR }}
          mkdir -p ./uploaded/images
          TAG=${{ github.sha }} docker compose -f docker-compose.yml up -d

          # Remove old unused backend images
          docker images --filter "reference=${{ secrets.DOCKER_USERNAME }}/bs-tournaments-backend:*" --format "{{.Repository}}:{{.Tag}}" | grep -v "${{ github.sha }}" | xargs -r docker rmi || true
          EOF
